services:
  backend:
    build:
      context: ./backend
    expose:
      - "8080"
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm start
    depends_on:
      - backend
    environment:
      - API_BASE_URL=${API_BASE_URL}
    restart: unless-stopped

  e2e-tests:
    build:
      context: ./e2e-tests
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - backend
    environment:
      E2E_BASE_URL_UI: "http://frontend:4200"
      E2E_BASE_URL_API: "http://backend:8080"
    command: mvn test
    volumes:
      - ./e2e-tests:/e2e-tests
      - ~/.m2:/root/.m2
    working_dir: /e2e-tests

  api-tests:
    build:
      context: ./api-tests
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      API_BASE_URL: "http://backend:8080"
    command: mvn test
    volumes:
      - ./api-tests:/api-tests
      - ~/.m2:/root/.m2
    working_dir: /api-tests

  e2e-selenium:
    build:
      context: ./e2e-selenium
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started
      db:
        condition: service_started
      selenium:
        condition: service_healthy
    environment:
      E2E_BASE_URL_UI: "http://frontend:4200"
      E2E_BASE_URL_API: "http://backend:8080"
      SELENIUM_REMOTE_URL: "http://selenium:4444/wd/hub"
    command: mvn clean test -Dmaven.test.failure.ignore=true
    shm_size: 2g
    volumes:
      - ./e2e-selenium:/e2e-selenium
      - ~/.m2:/root/.m2
    working_dir: /e2e-selenium

  selenium:
    image: seleniarm/standalone-chromium:latest  # ✅ ARM64-compatible image
    container_name: selenium
    shm_size: 2g
    ports:
      - "4444:4444"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4444/wd/hub/status || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    restart: unless-stopped

volumes:
  db_data:
