services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"

  frontend:
    build:
      dockerfile: Dockerfile.dev.dockerfile
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm start
    depends_on:
      - backend
    environment:
      - API_BASE_URL=${API_BASE_URL}
#
#  e2e-tests:
#    build:
#      context: ./e2e-tests
#    depends_on:
#      - frontend
#      - backend
#    environment:
#      - BASE_URL=${E2E_BASE_URL}
