services:
  backend:
    build:
      context: ./backend
    expose:
      - "8080"
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build:
      dockerfile: Dockerfile.dev.dockerfile
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm start
    depends_on:
      - backend
    environment:
      - API_BASE_URL=${API_BASE_URL}

  e2e-tests:
    build:
      context: ./e2e-tests
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - backend
    environment:
      E2E_BASE_URL_UI: "http://frontend:4200"
      E2E_BASE_URL_API: "http://backend:8080"
    command: mvn test
    volumes:
      - ./e2e-tests:/e2e-tests
      - ~/.m2:/root/.m2
    working_dir: /e2e-tests
    ports:
      - "8081:8080"

volumes:
  db_data:
