services:
  backend:
    build:
      context: ./backend
    expose:
      - "8080"
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      db:
        condition: service_started
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm start
    depends_on:
      - backend
    environment:
      - API_BASE_URL=${API_BASE_URL}
    networks:
      - app-network
    restart: unless-stopped

  selenium:
    image: seleniarm/standalone-chromium:latest
    container_name: selenium
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_SESSION_REQUEST_TIMEOUT=300
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4444/wd/hub/status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s

  e2e-selenium:
    build:
      context: ./e2e-selenium
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started
      selenium:
        condition: service_healthy
    environment:
      E2E_BASE_URL_UI: "http://frontend:4200"
      E2E_BASE_URL_API: "http://backend:8080"
      SELENIUM_REMOTE_URL: "http://selenium:4444/wd/hub"
    command: mvn clean test
    shm_size: 2g
    volumes:
      - ./e2e-selenium:/e2e-selenium:cached
      - ~/.m2:/root/.m2
    working_dir: /e2e-selenium
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
