name: Scheduled Test Runner

on:
  schedule:
    - cron: "*/3 * * * *" # every 3 minutes for testing
  workflow_dispatch: # optional manual trigger

jobs:
  trigger-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Integration Tests Workflow
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: run-integration-tests
          client-payload: '{"environment":"dev","cucumber_tags":"@regression"}'

  trigger-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger E2E Tests Workflow
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: run-e2e-tests
          client-payload: '{"environment":"dev","cucumber_tags":"@regression"}'
