name: E2E Tests (Selenium)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment configuration"
        required: false
        type: choice
        options: [dev, staging, prod]
        default: dev
      browser:
        description: "Select browser (or all)"
        required: false
        type: choice
        options: [chrome, firefox, all]
        default: chrome

permissions:
  contents: read
  pages: write
  id-token: write

run-name: "Selenium E2E on ${{ github.event.inputs.environment || 'dev' }} - Browser: ${{ github.event.inputs.browser || 'chrome' }}"

jobs:
  selenium-e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]
      max-parallel: 2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17 with Maven cache
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Start Selenium Grid + App Stack
        run: |
          ENV_NAME="${{ github.event.inputs.environment || 'dev' }}"
          BROWSER="${{ matrix.browser }}"
          INPUT_BROWSER="${{ github.event.inputs.browser || 'chrome' }}"

          if [ "$INPUT_BROWSER" != "all" ] && [ "$INPUT_BROWSER" != "$BROWSER" ]; then
            echo "⏭️ Skipping setup for $BROWSER because input=$INPUT_BROWSER"
            exit 0
          fi

          echo "🚀 Starting stack for $BROWSER | Env: $ENV_NAME"

          docker compose \
            --env-file ./config/.env.${ENV_NAME} \
            -f docker-compose.yml \
            up -d --build db backend frontend selenium-hub selenium-${BROWSER}

          echo "🕒 Waiting for frontend to be ready..."
          for i in {1..20}; do
            if curl -s http://localhost:4200 > /dev/null; then
              echo "✅ Frontend is up!"
              break
            fi
            echo "⏳ Waiting for frontend... ($i/20)"
            sleep 5
          done

      - name: Run E2E Tests on ${{ matrix.browser }}
        run: |
          ENV_NAME="${{ github.event.inputs.environment || 'dev' }}"
          BROWSER="${{ matrix.browser }}"
          INPUT_BROWSER="${{ github.event.inputs.browser || 'chrome' }}"

          if [ "$INPUT_BROWSER" != "all" ] && [ "$INPUT_BROWSER" != "$BROWSER" ]; then
            echo "⏭️ Skipping tests for $BROWSER because input=$INPUT_BROWSER"
            exit 0
          fi

          echo "🧪 Running tests on $BROWSER"

          docker compose \
            --env-file ./config/.env.${ENV_NAME} \
            -f docker-compose.yml \
            run --rm \
            -e TEST_BROWSER=${BROWSER} \
            e2e-selenium sh -c "
              cd /e2e-selenium && \
              mvn clean test \
                -Dtest.browser=${BROWSER} \
                -Dallure.results.directory=target/allure-results \
                -Dmaven.test.failure.ignore=true
            "

      - name: Upload Allure results (${{ matrix.browser }})
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results-${{ matrix.browser }}-${{ github.run_id }}
          path: e2e-selenium/target/allure-results
          retention-days: 7

      - name: Stop Docker services
        if: always()
        run: docker compose -f docker-compose.yml down -v

  allure-report-publish:
    needs: selenium-e2e-tests
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure JSON results (all browsers)
        uses: actions/download-artifact@v4
        with:
          path: allure-results
        continue-on-error: true

      - name: Merge Allure results
        run: |
          mkdir -p e2e-selenium/target/allure-results
          cp -r allure-results/*/* e2e-selenium/target/allure-results || true

      - name: Install Allure CLI
        run: |
          ALLURE_VERSION="2.27.0"
          curl -L -o "allure.zip" "https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/$ALLURE_VERSION/allure-commandline-$ALLURE_VERSION.zip"
          unzip allure.zip -d /opt
          sudo mv /opt/allure-$ALLURE_VERSION /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

      - name: Generate Allure HTML report
        run: |
          allure generate e2e-selenium/target/allure-results -o site --clean

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-report-${{ github.run_id }}
          path: site
          retention-days: 7

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
